version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12345abcdef"
s3_prefix = "sam-test"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

